version: '3.7'
services:
  comp-medimproc:
    build:
      context: ./
      dockerfile: docker/alpine/Dockerfile
      labels:
        io.simcore.name: '{"name": "Medical Image Processing - Computational Service"}'
        io.simcore.thumbnail: '{"thumbnail": "https://github.com/ITISFoundation/osparc-assets/blob/cb43207b6be2f4311c93cd963538d5718b41a023/assets/default-thumbnail-cookiecutter-osparc-service.png?raw=true"}'
        io.simcore.description: '{"description": "Medical Image Processing - Computational
          Service"}'
        io.simcore.key: '{"key": "simcore/services/comp/comp-medimproc"}'
        io.simcore.version: '{"version": "0.1.0"}'
        io.simcore.integration-version: '{"integration-version": "2.0.0"}'
        io.simcore.type: '{"type": "computational"}'
        io.simcore.authors: '{"authors": [{"name": "Javier Garcia Ordonez", "email":
          "ordonez@zmt.swiss", "affiliation": "ZMT ZurichMedTech AG"}]}'
        io.simcore.contact: '{"contact": "ordonez@zmt.swiss"}'
        io.simcore.inputs: '{"inputs": {"input_1": {"displayOrder": 1.0, "label":
          "input_1_label", "description": "The input 1 description", "type": "string",
          "fileToKeyMap": {"somefilename.ext": "input_1"}, "defaultValue": "some_value(optional)"},
          "input_2": {"displayOrder": 2.0, "label": "input_2_label", "description":
          "The input 2 description", "type": "string", "fileToKeyMap": {"somefilename.ext":
          "input_2"}, "defaultValue": "some_value(optional)"}, "input_3": {"displayOrder":
          3.0, "label": "input_3_label", "description": "The input 3 description",
          "type": "string", "fileToKeyMap": {"somefilename.ext": "input_3"}, "defaultValue":
          "some_value(optional)"}, "input_4": {"displayOrder": 4.0, "label": "input_4_label",
          "description": "The input 4 description", "type": "string", "fileToKeyMap":
          {"somefilename.ext": "input_4"}, "defaultValue": "some_value(optional)"}}}'
        io.simcore.outputs: '{"outputs": {"output_1": {"displayOrder": 1.0, "label":
          "output_1_label", "description": "The input 1 description", "type": "string",
          "fileToKeyMap": {"somefilename.ext": "output_1"}}, "output_2": {"displayOrder":
          2.0, "label": "output_2_label", "description": "The input 2 description",
          "type": "string", "fileToKeyMap": {"somefilename.ext": "output_2"}}, "output_3":
          {"displayOrder": 3.0, "label": "output_3_label", "description": "The input
          3 description", "type": "string", "fileToKeyMap": {"somefilename.ext": "output_3"}},
          "output_4": {"displayOrder": 4.0, "label": "output_4_label", "description":
          "The input 4 description", "type": "string", "fileToKeyMap": {"somefilename.ext":
          "output_4"}}}}'
        org.label-schema.build-date: '2024-08-28T16:18:24Z'
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: ''
        org.label-schema.vcs-url: ''
        simcore.service.restart-policy: no-restart
        simcore.service.settings: '[{"name": "Resources", "type": "Resources", "value":
          {"Limits": {"NanoCPUs": 1000000000, "MemoryBytes": 2147483648}}}]'
      target: production
    image: simcore/services/comp/comp-medimproc:0.1.0
